backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: homepage
    label: homepage
    files:
      - file: 'src/content/header.md'
        name: header
        label: Header
        fields:
          - {
              label: 'Relative Path',
              name: 'relpath',
              widget: 'hidden',
              default: '../../..',
            }
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'header',
            }
          - { label: Heading, name: heading, widget: string }
          - { label: Subeading, name: subheading, widget: string }
          - {
              label: Button,
              name: button,
              widget: object,
              fields:
                [
                  { label: Buttontext, name: buttontext, widget: string },
                  { label: Buttonlink, name: buttonlink, widget: string },
                ],
            }
          - {
              label: 'Background image',
              name: backgroundImage,
              widget: object,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Alt, name: alt, widget: string },
                ],
            }
      - file: 'src/content/first-block.md'
        name: firstBlock
        label: First block
        fields:
          - {
              label: 'Relative Path',
              name: 'relpath',
              widget: 'hidden',
              default: '../../..',
            }
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'first-block',
            }
          - { label: Heading, name: heading, widget: string }
          - { label: Body, name: body, widget: text }
          - {
              label: Button,
              name: button,
              widget: object,
              fields:
                [
                  { label: Buttontext, name: buttontext, widget: string },
                  { label: Buttonlink, name: buttonlink, widget: string },
                ],
            }
          - {
              label: Image,
              name: image,
              widget: object,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Alt, name: alt, widget: string },
                ],
            }
      - file: 'src/content/image-slide.md'
        name: imageSlide
        label: 'Image slide'
        fields:
          - {
              label: 'Relative Path',
              name: 'relpath',
              widget: 'hidden',
              default: '../../..',
            }
          - label: 'Images'
            name: 'images'
            widget: 'image'
            allow_multiple: true
            media_library:
              config:
                multiple: true
      - file: 'src/content/second-block.md'
        name: secondBlock
        label: 'Second block'
        fields:
          - {
              label: 'Relative Path',
              name: 'relpath',
              widget: 'hidden',
              default: '../../..',
            }
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'second-block',
            }
          - { label: Heading, name: heading, widget: string }
          - { label: Body, name: body, widget: text }
          - {
              label: Image,
              name: image,
              widget: object,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Alt, name: alt, widget: string },
                ],
            }
      - file: 'src/content/contact.md'
        name: contact
        label: Contact
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'contact',
            }
          - { label: Title, name: title, widget: string }
          - { label: Buttontext, name: buttontext, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Address, name: address, widget: text }
          - { label: Phone Jaap, name: phoneJaap, widget: number }
          - { label: Phone Rutger, name: phoneRutger, widget: number }
